'use strict';
const LegalPage = require('../models/LegalPage');
const SiteSettings = require('../models/SiteSettings');
const AuditLog = require('../models/AuditLog');
const logger = require('../utils/logger');

// Default content, moved here from what was hardcoded in
// app/legal/[slug].tsx — used only to seed a page the first time it's
// requested (findOne-or-create, same pattern as DeliveryConfig). After
// that, whatever's in the database is the real source of truth; editing
// these constants does nothing once a page has been created.
const DEFAULT_PAGES = {
  privacy: {
    title: 'Privacy Policy', icon: 'shield-lock-outline',
    sections: [
      { heading: 'What we collect', body: 'We collect the information you give us directly — your name, email, phone number, delivery address, and payment details — plus information generated by using WimaKit, like your order history, browsing activity, and device information.' },
      { heading: 'How we use it', body: 'We use your information to process orders, run deliveries, prevent fraud, provide customer support, and improve the app. We do not sell your personal data to third parties.' },
      { heading: 'Sharing with sellers and riders', body: 'When you place an order, the seller and assigned rider receive the information needed to fulfil it — your name, delivery address, and phone number. They cannot see your payment details.' },
      { heading: 'Your choices', body: 'You can review and edit your information from Edit Profile at any time, control notification preferences from Settings, and request account deletion from Settings → Privacy & Security → Delete Account.' },
      { heading: 'Data retention', body: 'We keep transaction records as required by financial regulations even after an account is deleted. Personal profile data is removed or anonymized once an account is deleted.' },
      { heading: 'Contact', body: 'Questions about this policy can be sent to privacy@wimakit.sl.' },
    ],
  },
  terms: {
    title: 'Terms of Service', icon: 'file-document-outline',
    sections: [
      { heading: 'Using WimaKit', body: 'By creating an account you agree to use WimaKit lawfully, provide accurate information, and not attempt to defraud buyers, sellers, or riders on the platform.' },
      { heading: 'Buyers', body: "Orders are a contract between you and the seller; WimaKit facilitates the transaction, payment escrow, and delivery. Funds are held in escrow until delivery is confirmed or a dispute is resolved." },
      { heading: 'Sellers', body: "Sellers must accurately describe products, fulfil orders promptly, and comply with WimaKit's moderation decisions. Repeated violations can result in store suspension." },
      { heading: 'Riders', body: 'Riders agree to deliver orders assigned to them in a timely, professional manner and are subject to performance review by WimaKit.' },
      { heading: 'Payments and payouts', body: "Seller and rider payouts are processed according to WimaKit's payout schedule and may be withheld pending an open dispute or fraud investigation." },
      { heading: 'Termination', body: 'WimaKit may suspend or terminate accounts that violate these terms, engage in fraud, or pose a risk to other users.' },
    ],
  },
  cookies: {
    title: 'Cookie Settings', icon: 'cookie-outline',
    sections: [
      { heading: 'How this applies to the app', body: 'The WimaKit mobile app does not use browser cookies. On the web version of WimaKit, we use a small number of essential session cookies needed to keep you logged in — these cannot be disabled without breaking login.' },
      { heading: 'Analytics', body: 'We use aggregated, non-identifying usage analytics to understand which features are used and where the app can be improved. This does not use tracking cookies or cross-site identifiers.' },
      { heading: 'No ad tracking', body: 'WimaKit does not use third-party advertising cookies or sell browsing data to advertisers.' },
    ],
  },
  help: {
    title: 'Help & Support', icon: 'help-circle-outline',
    sections: [
      { heading: 'Order issues', body: 'If an order hasn\'t arrived, arrived damaged, or doesn\'t match its description, open the order from your Orders tab and tap "Report an issue" — this opens a dispute that WimaKit\'s support team reviews.' },
      { heading: 'Payments and refunds', body: 'Refunds for cancelled or disputed orders are returned to your WimaKit wallet, or to your original payment method depending on how you paid. This typically takes 3–5 business days.' },
      { heading: 'Becoming a seller or rider', body: 'You can apply from your Profile tab. Store and rider applications are reviewed by WimaKit\'s team, usually within 24–48 hours.' },
      { heading: 'Account problems', body: 'For login issues, use "Forgot password" on the sign-in screen. For anything else — account access, verification, or something not covered here — reach out using the contact options below.' },
    ],
  },
};

// ─── Public reads ───────────────────────────────────────────────────────────

exports.getLegalPage = async (req, res) => {
  try {
    const { slug } = req.params;
    let page = await LegalPage.findOne({ slug, isActive: true }).lean();
    if (!page) {
      const fallback = DEFAULT_PAGES[slug] || DEFAULT_PAGES.help;
      page = await LegalPage.create({ slug, ...fallback });
      page = page.toObject();
    }
    res.json({ success: true, page });
  } catch (err) {
    logger.error('[getLegalPage]', err.message);
    res.status(500).json({ success: false, message: err.message });
  }
};

exports.getSiteSettings = async (req, res) => {
  try {
    let settings = await SiteSettings.findOne({ isActive: true }).lean();
    if (!settings) settings = (await SiteSettings.create({})).toObject();
    // Never expose internal fields to the public read.
    res.json({ success: true, settings: {
      supportPhone: settings.supportPhone,
      supportEmail: settings.supportEmail,
      supportWhatsApp: settings.supportWhatsApp,
    } });
  } catch (err) {
    logger.error('[getSiteSettings]', err.message);
    res.status(500).json({ success: false, message: err.message });
  }
};

// ─── Admin writes ───────────────────────────────────────────────────────────

exports.listLegalPages = async (req, res) => {
  try {
    const pages = await LegalPage.find().sort({ slug: 1 }).lean();
    res.json({ success: true, pages });
  } catch (err) { res.status(500).json({ message: err.message }); }
};

exports.updateLegalPage = async (req, res) => {
  try {
    const { slug } = req.params;
    const { title, icon, sections } = req.body;
    if (!Array.isArray(sections) || sections.some((s) => !s.heading || !s.body)) {
      return res.status(400).json({ message: 'sections must be an array of { heading, body }' });
    }
    let page = await LegalPage.findOne({ slug });
    if (!page) page = new LegalPage({ slug, ...(DEFAULT_PAGES[slug] || DEFAULT_PAGES.help) });
    page.title = title ?? page.title;
    page.icon = icon ?? page.icon;
    page.sections = sections;
    page.updatedBy = req.user._id;
    page.version += 1;
    await page.save();

    await AuditLog.create({ admin: req.user._id, action: 'UPDATE_SETTINGS', targetId: page._id, targetModel: 'LegalPage', details: `Updated legal page: ${slug}`, ipAddress: req.ip }).catch(() => {});
    res.json({ success: true, page });
  } catch (err) { res.status(500).json({ message: err.message }); }
};

exports.updateSiteSettings = async (req, res) => {
  try {
    const { supportPhone, supportEmail, supportWhatsApp } = req.body;
    let settings = await SiteSettings.findOne({ isActive: true });
    if (!settings) settings = new SiteSettings({});
    if (supportPhone) settings.supportPhone = supportPhone;
    if (supportEmail) settings.supportEmail = supportEmail;
    if (supportWhatsApp) settings.supportWhatsApp = supportWhatsApp;
    settings.updatedBy = req.user._id;
    settings.version += 1;
    await settings.save();

    await AuditLog.create({ admin: req.user._id, action: 'UPDATE_SETTINGS', targetId: settings._id, targetModel: 'SiteSettings', details: 'Updated site support settings', ipAddress: req.ip }).catch(() => {});
    res.json({ success: true, settings });
  } catch (err) { res.status(500).json({ message: err.message }); }
};
