import React from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, Linking, ActivityIndicator } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useRouter, useLocalSearchParams } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useTheme } from '../../context/ThemeContext';
import { Spacing, FontSize } from '../../constants/theme';
import { useLegalPage, useSiteSettings } from '../../hooks/useApi';

// This content used to live only here, hardcoded in the app bundle —
// correct, real copy (a prior fix from dead no-op buttons), but changing a
// single word meant a full app store release, and the support phone number
// was duplicated in app/about.tsx too. It's now served from
// GET /api/content/legal/:slug (admin-editable — see the admin Content
// module), cached via the same AsyncStorage-persisted React Query setup as
// everything else in the app, so it still works offline after the first
// successful load. FALLBACK below is now only for the genuinely worst
// case — first-ever launch, no connection yet, nothing cached — so the
// screen never has to show a blank page or a spinner with no way out.
const FALLBACK: Record<string, { title: string; icon: string; sections: { heading: string; body: string }[] }> = {
  privacy: {
    title: 'Privacy Policy',
    icon: 'shield-lock-outline',
    sections: [
      { heading: 'What we collect', body: 'We collect the information you give us directly — your name, email, phone number, delivery address, and payment details — plus information generated by using WimaKit, like your order history, browsing activity, and device information.' },
      { heading: 'How we use it', body: 'We use your information to process orders, run deliveries, prevent fraud, provide customer support, and improve the app. We do not sell your personal data to third parties.' },
      { heading: 'Your choices', body: 'You can review and edit your information from Edit Profile at any time, control notification preferences from Settings, and request account deletion from Settings → Privacy & Security → Delete Account.' },
    ],
  },
  terms: {
    title: 'Terms of Service',
    icon: 'file-document-outline',
    sections: [
      { heading: 'Using WimaKit', body: 'By creating an account you agree to use WimaKit lawfully, provide accurate information, and not attempt to defraud buyers, sellers, or riders on the platform.' },
      { heading: 'Buyers', body: 'Orders are a contract between you and the seller; WimaKit facilitates the transaction, payment escrow, and delivery.' },
    ],
  },
  cookies: {
    title: 'Cookie Settings',
    icon: 'cookie-outline',
    sections: [
      { heading: 'How this applies to the app', body: 'The WimaKit mobile app does not use browser cookies.' },
    ],
  },
  help: {
    title: 'Help & Support',
    icon: 'help-circle-outline',
    sections: [
      { heading: 'Order issues', body: 'If an order hasn\'t arrived, arrived damaged, or doesn\'t match its description, open the order from your Orders tab and tap "Report an issue".' },
      { heading: 'Account problems', body: 'For login issues, use "Forgot password" on the sign-in screen.' },
    ],
  },
};

export default function LegalScreen() {
  const router = useRouter();
  const { colors } = useTheme();
  const { slug: rawSlug } = useLocalSearchParams<{ slug: string }>();
  const slug = (rawSlug as string) || 'help';

  const { data: page, isLoading } = useLegalPage(slug);
  const { data: settings } = useSiteSettings();
  const supportPhone = settings?.supportPhone || '+23276000000';
  const display = page ?? { slug, ...(FALLBACK[slug] ?? FALLBACK.help) };

  return (
    <SafeAreaView style={[styles.root, { backgroundColor: colors.background }]} edges={['top']}>
      <View style={[styles.header, { borderBottomColor: colors.border }]}>
        <TouchableOpacity onPress={() => router.back()} style={styles.backBtn}>
          <MaterialCommunityIcons name="arrow-left" size={22} color={colors.textPrimary} />
        </TouchableOpacity>
        <Text style={[styles.headerTitle, { color: colors.textPrimary }]}>{display.title}</Text>
        <View style={{ width: 22 }} />
      </View>

      {isLoading && !page ? (
        <ActivityIndicator color={colors.primary} style={{ marginTop: 40 }} />
      ) : (
        <ScrollView contentContainerStyle={styles.scroll}>
          <View style={[styles.iconWrap, { backgroundColor: colors.primary + '15' }]}>
            <MaterialCommunityIcons name={display.icon as any} size={28} color={colors.primary} />
          </View>

          {display.sections.map((sec: { heading: string; body: string }) => (
            <View key={sec.heading} style={{ marginBottom: Spacing.lg }}>
              <Text style={[styles.sectionHeading, { color: colors.textPrimary }]}>{sec.heading}</Text>
              <Text style={[styles.sectionBody, { color: colors.textSecondary }]}>{sec.body}</Text>
            </View>
          ))}

          {slug === 'help' && (
            <TouchableOpacity
              style={[styles.contactBtn, { backgroundColor: colors.primary }]}
              onPress={() => Linking.openURL(`tel:${supportPhone}`)}
            >
              <MaterialCommunityIcons name="phone" size={18} color="#fff" />
              <Text style={styles.contactBtnText}>Call Support: {supportPhone}</Text>
            </TouchableOpacity>
          )}
        </ScrollView>
      )}
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1 },
  header: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: Spacing.lg, paddingVertical: Spacing.md, borderBottomWidth: StyleSheet.hairlineWidth,
  },
  backBtn: { padding: 4 },
  headerTitle: { fontSize: FontSize.lg, fontWeight: '800' },
  scroll: { padding: Spacing.xl, paddingBottom: Spacing.xxl * 2 },
  iconWrap: { width: 56, height: 56, borderRadius: 28, alignItems: 'center', justifyContent: 'center', marginBottom: Spacing.lg },
  sectionHeading: { fontSize: FontSize.md, fontWeight: '800', marginBottom: 6 },
  sectionBody: { fontSize: FontSize.sm, lineHeight: 21 },
  contactBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, paddingVertical: 14, borderRadius: 14, marginTop: Spacing.md },
  contactBtnText: { color: '#fff', fontWeight: '800', fontSize: 14 },
});
