import React from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, Linking } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useRouter, useLocalSearchParams } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useTheme } from '../../context/ThemeContext';
import { Spacing, FontSize } from '../../constants/theme';

// One shared screen for every static info page (Privacy Policy, Terms of
// Service, Cookie Settings, Help & Support). These were previously
// `onPress={() => {}}` no-ops in settings.tsx / profile-tab.tsx — tapping
// them did nothing at all. Real legal copy should eventually be reviewed by
// counsel before shipping to production; this gives users something
// substantive in the meantime instead of a dead button.
const PAGES: Record<string, { title: string; icon: string; sections: { heading: string; body: string }[] }> = {
  privacy: {
    title: 'Privacy Policy',
    icon: 'shield-lock-outline',
    sections: [
      { heading: 'What we collect', body: 'We collect the information you give us directly — your name, email, phone number, delivery address, and payment details — plus information generated by using WimaKit, like your order history, browsing activity, and device information.' },
      { heading: 'How we use it', body: 'We use your information to process orders, run deliveries, prevent fraud, provide customer support, and improve the app. We do not sell your personal data to third parties.' },
      { heading: 'Sharing with sellers and riders', body: 'When you place an order, the seller and assigned rider receive the information needed to fulfil it — your name, delivery address, and phone number. They cannot see your payment details.' },
      { heading: 'Your choices', body: 'You can review and edit your information from Edit Profile at any time, control notification preferences from Settings, and request account deletion from Settings → Privacy & Security → Delete Account.' },
      { heading: 'Data retention', body: 'We keep transaction records as required by financial regulations even after an account is deleted. Personal profile data is removed or anonymized once an account is deleted.' },
      { heading: 'Contact', body: 'Questions about this policy can be sent to privacy@wimakit.sl.' },
    ],
  },
  terms: {
    title: 'Terms of Service',
    icon: 'file-document-outline',
    sections: [
      { heading: 'Using WimaKit', body: 'By creating an account you agree to use WimaKit lawfully, provide accurate information, and not attempt to defraud buyers, sellers, or riders on the platform.' },
      { heading: 'Buyers', body: 'Orders are a contract between you and the seller; WimaKit facilitates the transaction, payment escrow, and delivery. Funds are held in escrow until delivery is confirmed or a dispute is resolved.' },
      { heading: 'Sellers', body: 'Sellers must accurately describe products, fulfil orders promptly, and comply with WimaKit\'s moderation decisions. Repeated violations can result in store suspension.' },
      { heading: 'Riders', body: 'Riders agree to deliver orders assigned to them in a timely, professional manner and are subject to performance review by WimaKit.' },
      { heading: 'Payments and payouts', body: 'Seller and rider payouts are processed according to WimaKit\'s payout schedule and may be withheld pending an open dispute or fraud investigation.' },
      { heading: 'Termination', body: 'WimaKit may suspend or terminate accounts that violate these terms, engage in fraud, or pose a risk to other users.' },
    ],
  },
  cookies: {
    title: 'Cookie Settings',
    icon: 'cookie-outline',
    sections: [
      { heading: 'How this applies to the app', body: 'The WimaKit mobile app does not use browser cookies. On the web version of WimaKit, we use a small number of essential session cookies needed to keep you logged in — these cannot be disabled without breaking login.' },
      { heading: 'Analytics', body: 'We use aggregated, non-identifying usage analytics to understand which features are used and where the app can be improved. This does not use tracking cookies or cross-site identifiers.' },
      { heading: 'No ad tracking', body: 'WimaKit does not use third-party advertising cookies or sell browsing data to advertisers.' },
    ],
  },
  help: {
    title: 'Help & Support',
    icon: 'help-circle-outline',
    sections: [
      { heading: 'Order issues', body: 'If an order hasn\'t arrived, arrived damaged, or doesn\'t match its description, open the order from your Orders tab and tap "Report an issue" — this opens a dispute that WimaKit\'s support team reviews.' },
      { heading: 'Payments and refunds', body: 'Refunds for cancelled or disputed orders are returned to your WimaKit wallet, or to your original payment method depending on how you paid. This typically takes 3–5 business days.' },
      { heading: 'Becoming a seller or rider', body: 'You can apply from your Profile tab. Store and rider applications are reviewed by WimaKit\'s team, usually within 24–48 hours.' },
      { heading: 'Account problems', body: 'For login issues, use "Forgot password" on the sign-in screen. For anything else — account access, verification, or something not covered here — reach out using the contact options below.' },
    ],
  },
};

export default function LegalScreen() {
  const router = useRouter();
  const { colors } = useTheme();
  const { slug } = useLocalSearchParams<{ slug: string }>();
  const page = PAGES[slug as string] ?? PAGES.help;

  return (
    <SafeAreaView style={[styles.root, { backgroundColor: colors.background }]} edges={['top']}>
      <View style={[styles.header, { borderBottomColor: colors.border }]}>
        <TouchableOpacity onPress={() => router.back()} style={styles.backBtn}>
          <MaterialCommunityIcons name="arrow-left" size={22} color={colors.textPrimary} />
        </TouchableOpacity>
        <Text style={[styles.headerTitle, { color: colors.textPrimary }]}>{page.title}</Text>
        <View style={{ width: 22 }} />
      </View>

      <ScrollView contentContainerStyle={styles.scroll}>
        <View style={[styles.iconWrap, { backgroundColor: colors.primary + '15' }]}>
          <MaterialCommunityIcons name={page.icon as any} size={28} color={colors.primary} />
        </View>

        {page.sections.map((sec) => (
          <View key={sec.heading} style={{ marginBottom: Spacing.lg }}>
            <Text style={[styles.sectionHeading, { color: colors.textPrimary }]}>{sec.heading}</Text>
            <Text style={[styles.sectionBody, { color: colors.textSecondary }]}>{sec.body}</Text>
          </View>
        ))}

        {slug === 'help' && (
          <TouchableOpacity
            style={[styles.contactBtn, { backgroundColor: colors.primary }]}
            onPress={() => Linking.openURL('tel:+23276000000')}
          >
            <MaterialCommunityIcons name="phone" size={18} color="#fff" />
            <Text style={styles.contactBtnText}>Call Support: +232 76 000 000</Text>
          </TouchableOpacity>
        )}
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1 },
  header: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: Spacing.lg, paddingVertical: Spacing.md, borderBottomWidth: StyleSheet.hairlineWidth,
  },
  backBtn: { padding: 4 },
  headerTitle: { fontSize: FontSize.lg, fontWeight: '800' },
  scroll: { padding: Spacing.xl, paddingBottom: Spacing.xxl * 2 },
  iconWrap: { width: 56, height: 56, borderRadius: 28, alignItems: 'center', justifyContent: 'center', marginBottom: Spacing.lg },
  sectionHeading: { fontSize: FontSize.md, fontWeight: '800', marginBottom: 6 },
  sectionBody: { fontSize: FontSize.sm, lineHeight: 21 },
  contactBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, paddingVertical: 14, borderRadius: 14, marginTop: Spacing.md },
  contactBtnText: { color: '#fff', fontWeight: '800', fontSize: 14 },
});
